# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 06 Pack ModelBinders

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Pack
      run: dotnet pack ./src/AD.BaseTypes.ModelBinders/AD.BaseTypes.ModelBinders.csproj --configuration Release --output out
    - uses: actions/upload-artifact@v3
      with:
        name: ModelBinders
        path: out/*
      